import boy1 from "@/assets/avatars/boy-1.svg";
import boy2 from "@/assets/avatars/boy-2.svg";
import boy3 from "@/assets/avatars/boy-3.svg";
import boy4 from "@/assets/avatars/boy-4.svg";
import girl1 from "@/assets/avatars/girl-1.svg";
import girl2 from "@/assets/avatars/girl-2.svg";
import girl3 from "@/assets/avatars/girl-3.svg";
import girl4 from "@/assets/avatars/girl-4.svg";

/**
 * The built-in profile avatars. They replaced uploaded photos: a profile
 * stores only the id of the one picked (`profiles.avatar_id`), and NULL means
 * "the default for my gender". The art is generated by
 * scripts/generate-avatars.cjs; the database only accepts these ids
 * (profiles_avatar_id_check).
 */
export type AvatarGender = "male" | "female";

export interface AvatarDef {
  id: string;
  gender: AvatarGender;
  src: string;
  name: { ar: string; en: string };
}

export const AVATARS: AvatarDef[] = [
  { id: "boy-1", gender: "male", src: boy1, name: { ar: "البطل", en: "The Hero" } },
  { id: "boy-2", gender: "male", src: boy2, name: { ar: "المرتّب", en: "The Neat One" } },
  { id: "boy-3", gender: "male", src: boy3, name: { ar: "الكيرلي", en: "The Curly One" } },
  { id: "boy-4", gender: "male", src: boy4, name: { ar: "أبو لحية", en: "The Bearded One" } },
  { id: "girl-1", gender: "female", src: girl1, name: { ar: "الشعر الطويل", en: "Long Hair" } },
  { id: "girl-2", gender: "female", src: girl2, name: { ar: "حجاب برتقالي", en: "Orange Hijab" } },
  { id: "girl-3", gender: "female", src: girl3, name: { ar: "السمراء", en: "The Brunette" } },
  { id: "girl-4", gender: "female", src: girl4, name: { ar: "حجاب كحلي", en: "Navy Hijab" } },
];

const BY_ID = new Map(AVATARS.map((a) => [a.id, a]));

/** Who you get before picking one. No gender on file (every account made
 *  before the welcome flow asked) gets the app's hero. */
export const DEFAULT_AVATAR: Record<AvatarGender, string> = { male: "boy-1", female: "girl-2" };

export function resolveAvatar(avatarId?: string | null, gender?: string | null): AvatarDef {
  const picked = avatarId ? BY_ID.get(avatarId) : undefined;
  if (picked) return picked;
  return BY_ID.get(gender === "female" ? DEFAULT_AVATAR.female : DEFAULT_AVATAR.male)!;
}

/** Circle colours. One per user, fixed, so a leaderboard of mostly the same
 *  character still reads as different people. */
const BACKGROUNDS = ["#1CB0F6", "#FFC800", "#58CC02", "#CE82FF", "#00CD9C", "#FF86D0"];

export function avatarBackground(seed?: string | null): string {
  if (!seed) return BACKGROUNDS[0];
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return BACKGROUNDS[h % BACKGROUNDS.length];
}
