project_id = "zmkgbotvmfpsrvvgztxn"

[functions.create-backup]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.iron-coach]
verify_jwt = true
